### ISSUE TITLE
wxbot-puppet-bridge 是可以直接使用，还是需要作为wechaty得puppet使用？

### ISSUE THREAD

**Issue by guanxb9581** [yzqzy/wxbot-puppet-bridge#1]
我是想用wxbox-puppet-bridge替换wechaty-puppet-padlocal
文件代码：
```import { WeChatSdkPuppetBridge_3_9_10_19 as PuppetBridge } from  'wxbot-puppet-bridge'
import { log, ScanStatus, WechatyBuilder } from "wechaty";
const puppet = new PuppetBridge({
  apiUrl: 'http://127.0.0.1:8888',
  protocol: 'ws' 
})
const bot = WechatyBuilder.build({
  name: "PadLocalDemo",
  puppet,
})  .on("message", async (message) => {
    log.info('wecat on message', message)
    if (message.talker()?.id != undefined && !message.self()) {     
      if (message.type() == PUPPET.types.Message.Text || message.type() == PUPPET.types.Message.Location  ) {
        //保存聊天
        saveMessage(message, '');

        if (message.room()?.id != undefined) {
          log.info(LOGPRE, `on message: ${message.toString()}`); 
          // //会话聊天及结束
          // checkSignature(message, myName, signatureObj);
          // //开启会话
          // setSignature(message, myName, signatureObj);
          checkKeyword(message)
          bindListen(bot, message)

        } else {
          setTalkerSignature(message, signatureObj);
          privateChat(bot, message)
        }
      }else{
        getMessagePayload(message,0)
        
      }
    }
  })```

运行项目的时候，我看到了INFO PuppetBridge onMessage() message  打印出来的信息，但却看不到wecat on message的信息，反而收到GError: message not found for id: 746285378838785900报错信息，想问下这个怎么解决？

**Comment by yzqzy** [comment]
@guanxb9581 适配的功能还不太完整，我再根据你这个案例适配下 message 相关的内容。

目前 message 事件可以兼容，`.room()` 包括 `bot` 还未实现。

**Comment by yzqzy** [comment]
> 我是想用wxbox-puppet-bridge替换wechaty-puppet-padlocal 文件代码： `import { WeChatSdkPuppetBridge_3_9_10_19 as PuppetBridge } from 'wxbot-puppet-bridge' import { log, ScanStatus, WechatyBuilder } from "wechaty"; const puppet = new PuppetBridge({ apiUrl: 'http://127.0.0.1:8888', protocol: 'ws' }) const bot = WechatyBuilder.build({ name: "PadLocalDemo", puppet, }) .on("message", async (message) => { log.info('wecat on message', message) if (message.talker()?.id != undefined && !message.self()) { if (message.type() == PUPPET.types.Message.Text || message.type() == PUPPET.types.Message.Location ) { //保存聊天 saveMessage(message, '');
> 
> ```
>     if (message.room()?.id != undefined) {
>       log.info(LOGPRE, `on message: ${message.toString()}`); 
>       // //会话聊天及结束
>       // checkSignature(message, myName, signatureObj);
>       // //开启会话
>       // setSignature(message, myName, signatureObj);
>       checkKeyword(message)
>       bindListen(bot, message)
> 
>     } else {
>       setTalkerSignature(message, signatureObj);
>       privateChat(bot, message)
>     }
>   }else{
>     getMessagePayload(message,0)
>     
>   }
> }
> ```
> 
> })`
> 
> 运行项目的时候，我看到了INFO PuppetBridge onMessage() message 打印出来的信息，但却看不到wecat on message的信息，反而收到GError: message not found for id: 746285378838785900报错信息，想问下这个怎么解决？

可以直接使用，应该是你使用的功能还没有适配完成，适配完成我会提供案例到 `examples` 文件夹。

**Comment by guanxb9581** [comment]
收到，辛苦了

**Comment by guanxb9581** [comment]
大佬，问一下，bot和兼容wechaty的Message接口大概什么时候可以适配完成呢？

**Comment by yzqzy** [comment]
> 大佬，问一下，bot和兼容wechaty的Message接口大概什么时候可以适配完成呢？

最晚这周末会处理完成，message 会优先处理下。

**Comment by yzqzy** [comment]
> 大佬，问一下，bot和兼容wechaty的Message接口大概什么时候可以适配完成呢？

目前已支持 bot、message 文本消息收发，更多功能正在适配中。
