### ISSUE TITLE
 bot.Room.findAll()这个方法并没能拿到值，请问适配了吗

### ISSUE THREAD

**Issue by zzxiaotian** [yzqzy/wxbot-puppet-bridge#2]
export async function syncWxRoomInfo(bot: any) {
  try {
    const allRooms = await bot.Room.findAll();
  const wxRooms = new Array;

**Comment by yzqzy** [comment]
> export async function syncWxRoomInfo(bot: any) { try { const allRooms = await bot.Room.findAll(); const wxRooms = new Array;

最新版本已修复，1.0.13 。
