### ISSUE TITLE
读取消息的图片路径错误

### ISSUE THREAD

**Issue by zzxiaotian** [yzqzy/wxbot-puppet-bridge#3]
![Snipaste_2024-07-30_16-35-16](https://github.com/user-attachments/assets/8d70246f-8305-4a2e-940e-ac956e617a3c)

**Comment by zzxiaotian** [comment]
好的，感谢

**Comment by yzqzy** [comment]
> 好的，感谢

最新版本已对 图片、视频、文件 等格式进行处理。[点击](https://github.com/yzqzy/wxbot-puppet-bridge/blob/main/examples/wechatsdk-bot-file-analysis.ts) 可查看测试用例。

**Comment by zzxiaotian** [comment]
messageImage AxiosError: read ECONNRESET
    at Function.from (E:\wecat-order\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (E:\wecat-order\node_modules\axios\lib\adapters\http.js:610:25)
    at RedirectableRequest.emit (node:events:511:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.<anonymous> (E:\wecat-order\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:511:28)
    at Socket.emit (node:domain:489:12)
    at Axios.request (E:\wecat-order\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request.post (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-api.js:18:21)
    at async Bridge.cdnDownload (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-agent.js:324:21)
    at async PuppetBridge.messageImage (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\bridge\wechatsdk-3.9.10.19.js:542:17)
    at async WechatifiedUserClass.thumbnail (E:\wecat-order\node_modules\wechaty\src\user-modules\image.ts:50:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -4077,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.7.2',
      'Content-Length': '422',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://127.0.0.1:8888',
    method: 'post',
    url: '/api/',
    data: '{"type":88,"fileid":"3057020100044b30490201000204ab5e6e6402032f84110204e5ba587d020466ab00fd042436653234313062352d663633392d346164322d616664382d653165373562343733363834020405250a020201000
405004c55cd00","aeskey":"814a583228530b2113bcbd0c368ea583","fileType":3,"savePath":"C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\wxid_diut1wd1cwci12\\\\FileStorage\\\\File\\\\2024-0
8\\\\message_814a583228530b2113bcbd0c368ea583_thumb.png"}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '8888',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 422,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '422',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Content-Length: 422\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:8888\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://127.0.0.1:8888/api/',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
21:41:42 INFO [PadLocalDemo] get message image, hd0: wxbot-puppet-bridge

**Comment by zzxiaotian** [comment]
![b66ba2f018335bcebdf63eb81c6460c](https://github.com/user-attachments/assets/45aca30e-2e88-40bc-b72c-50a60b58e8d2)
调试的时候报了这个错误

**Comment by zzxiaotian** [comment]
messageImage AxiosError: read ECONNRESET
    at Function.from (E:\wecat-order\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (E:\wecat-order\node_modules\axios\lib\adapters\http.js:610:25)
    at RedirectableRequest.emit (node:events:511:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.<anonymous> (E:\wecat-order\node_modules\follow-redirects\index.js:38:24)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:511:28)
    at Socket.emit (node:domain:489:12)
    at Axios.request (E:\wecat-order\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request.post (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-api.js:18:21)
    at async Bridge.cdnDownload (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-agent.js:324:21)
    at async PuppetBridge.messageImage (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\bridge\wechatsdk-3.9.10.19.js:542:17)
    at async WechatifiedUserClass.thumbnail (E:\wecat-order\node_modules\wechaty\src\user-modules\image.ts:50:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -4077,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.7.2',
      'Content-Length': '422',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://127.0.0.1:8888',
    method: 'post',
    url: '/api/',
    data: '{"type":88,"fileid":"3057020100044b30490201000204ab5e6e6402032f84110204e5ba587d020466ab00fd042436653234313062352d663633392d346164322d616664382d653165373562343733363834020405250a020201000
405004c55cd00","aeskey":"814a583228530b2113bcbd0c368ea583","fileType":3,"savePath":"C:\\\\Users\\\\Administrator\\\\Documents\\\\WeChat Files\\\\wxid_diut1wd1cwci12\\\\FileStorage\\\\File\\\\2024-0
8\\\\message_814a583228530b2113bcbd0c368ea583_thumb.png"}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '127.0.0.1',
      port: '8888',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 422,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '422',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.7.2\r\n' +
        'Content-Length: 422\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 127.0.0.1:8888\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://127.0.0.1:8888/api/',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
21:41
![b66ba2f018335bcebdf63eb81c6460c](https://github.com/user-attachments/assets/dabefda4-e4b2-4c6b-a99b-c4624a42835b)
:42 INFO [PadLocalDemo] get message image, hd0: wxbot-puppet-bridge
 调试的时候调用图片中的方法报了上面的错误

**Comment by yzqzy** [comment]
> messageImage AxiosError: read ECONNRESET at Function.from (E:\wecat-order\node_modules\axios\lib\core\AxiosError.js:89:14) at RedirectableRequest.handleRequestError (E:\wecat-order\node_modules\axios\lib\adapters\http.js:610:25) at RedirectableRequest.emit (node:events:511:28) at RedirectableRequest.emit (node:domain:489:12) at ClientRequest. (E:\wecat-order\node_modules\follow-redirects\index.js:38:24) at ClientRequest.emit (node:events:511:28) at ClientRequest.emit (node:domain:489:12) at Socket.socketErrorListener (node:_http_client:495:9) at Socket.emit (node:events:511:28) at Socket.emit (node:domain:489:12) at Axios.request (E:\wecat-order\node_modules\axios\lib\core\Axios.js:45:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async Request.post (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-api.js:18:21) at async Bridge.cdnDownload (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\agents\wechatsdk-agent.js:324:21) at async PuppetBridge.messageImage (E:\wecat-order\node_modules\wxbot-puppet-bridge\dist\bridge\wechatsdk-3.9.10.19.js:542:17) at async WechatifiedUserClass.thumbnail (E:\wecat-order\node_modules\wechaty\src\user-modules\image.ts:50:21) { syscall: 'read', code: 'ECONNRESET', errno: -4077, config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [ 'xhr', 'http', 'fetch' ], transformRequest: [ [Function: transformRequest] ], transformResponse: [ [Function: transformResponse] ], timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, env: { FormData: [Function], Blob: [class Blob] }, validateStatus: [Function: validateStatus], headers: Object [AxiosHeaders] { Accept: 'application/json, text/plain, _/_', 'Content-Type': 'application/json', 'User-Agent': 'axios/1.7.2', 'Content-Length': '422', 'Accept-Encoding': 'gzip, compress, deflate, br' }, baseURL: 'http://127.0.0.1:8888', method: 'post', url: '/api/', data: '{"type":88,"fileid":"3057020100044b30490201000204ab5e6e6402032f84110204e5ba587d020466ab00fd042436653234313062352d663633392d346164322d616664382d653165373562343733363834020405250a020201000 405004c55cd00","aeskey":"814a583228530b2113bcbd0c368ea583","fileType":3,"savePath":"C:\\Users\\Administrator\\Documents\\WeChat Files\\wxid_diut1wd1cwci12\\FileStorage\\File\\2024-0 8\\message_814a583228530b2113bcbd0c368ea583_thumb.png"}' }, request: <ref *1> Writable { _writableState: WritableState { objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: false, ended: false, finished: false, destroyed: false, decodeStrings: true, defaultEncoding: 'utf8', length: 0, writing: false, corked: 0, sync: true, bufferProcessing: false, onwrite: [Function: bound onwrite], writecb: null, writelen: 0, afterWriteTickInfo: null, buffered: [], bufferedIndex: 0, allBuffers: true, allNoop: true, pendingcb: 0, constructed: true, prefinished: false, errorEmitted: false, emitClose: true, autoDestroy: true, errored: null, closed: false, closeEmitted: false, [Symbol(kOnFinished)]: [] }, _events: [Object: null prototype] { response: [Function: handleResponse], error: [Function: handleRequestError], socket: [Function: handleRequestSocket] }, _eventsCount: 3, _maxListeners: undefined, _options: { maxRedirects: 21, maxBodyLength: Infinity, protocol: 'http:', path: '/api/', method: 'POST', headers: [Object: null prototype], agents: [Object], auth: undefined, family: undefined, beforeRedirect: [Function: dispatchBeforeRedirect], beforeRedirects: [Object], hostname: '127.0.0.1', port: '8888', agent: undefined, nativeProtocols: [Object], pathname: '/api/' }, _ended: true, _ending: true, _redirectCount: 0, _redirects: [], _requestBodyLength: 422, _requestBodyBuffers: [ [Object] ], _onNativeResponse: [Function (anonymous)], _currentRequest: ClientRequest { _events: [Object: null prototype], _eventsCount: 7, _maxListeners: undefined, outputData: [], outputSize: 0, writable: true, destroyed: false, _last: false, chunkedEncoding: false, shouldKeepAlive: true, maxRequestsOnConnectionReached: false, _defaultKeepAlive: true, useChunkedEncodingByDefault: true, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, strictContentLength: false, _contentLength: '422', _hasBody: true, _trailer: '', finished: true, _headerSent: true, _closed: false, socket: [Socket], _header: 'POST /api/ HTTP/1.1\r\n' + 'Accept: application/json, text/plain, _/_\r\n' + 'Content-Type: application/json\r\n' + 'User-Agent: axios/1.7.2\r\n' + 'Content-Length: 422\r\n' + 'Accept-Encoding: gzip, compress, deflate, br\r\n' + 'Host: 127.0.0.1:8888\r\n' + 'Connection: keep-alive\r\n' + '\r\n', _keepAliveTimeout: 0, _onPendingData: [Function: nop], agent: [Agent], socketPath: undefined, method: 'POST', maxHeaderSize: undefined, insecureHTTPParser: undefined, joinDuplicateHeaders: undefined, path: '/api/', _ended: false, res: null, aborted: false, timeoutCb: [Function: emitRequestTimeout], upgradeOrConnect: false, parser: null, maxHeadersCount: null, reusedSocket: true, host: '127.0.0.1', protocol: 'http:', _redirectable: [Circular *1], [Symbol(kCapture)]: false, [Symbol(kBytesWritten)]: 0, [Symbol(kNeedDrain)]: false, [Symbol(corked)]: 0, [Symbol(kOutHeaders)]: [Object: null prototype], [Symbol(errored)]: null, [Symbol(kHighWaterMark)]: 16384, [Symbol(kUniqueHeaders)]: null }, _currentUrl: 'http://127.0.0.1:8888/api/', [Symbol(kCapture)]: false }, cause: Error: read ECONNRESET at TCP.onStreamRead (node:internal/stream_base_commons:217:20) at TCP.callbackTrampoline (node:internal/async_hooks:130:17) { errno: -4077, code: 'ECONNRESET', syscall: 'read' } } 21:41 ![b66ba2f018335bcebdf63eb81c6460c](https://private-user-images.githubusercontent.com/13702816/354820948-dabefda4-e4b2-4c6b-a99b-c4624a42835b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MjIwMDEsIm5iZiI6MTcyMjcyMTcwMSwicGF0aCI6Ii8xMzcwMjgxNi8zNTQ4MjA5NDgtZGFiZWZkYTQtZTRiMi00YzZiLWE5OWItYzQ2MjRhNDI4MzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDIxNDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YWM5N2QwYzhiYjZkZmU5MzZjMTZhYjkzMGI4MTA4MTAzM2NmMGQzOGViZDQyNTgzYjE2ZGU2NmYyMDMxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LzF6ySO5vz46kfoDZt2dkW4nNgxINS7CgruI-1vHH_s) :42 INFO [PadLocalDemo] get message image, hd0: wxbot-puppet-bridge 调试的时候调用图片中的方法报了上面的错误

使用同样的参数未复现该问题。

1. 是否所有图片都不能下载
2. 是否具有相关文件路径的操作权限

**Comment by zzxiaotian** [comment]
![1](https://github.com/user-attachments/assets/7dab3cbb-de52-4455-9b2c-38713c5445e8)
![2](https://github.com/user-attachments/assets/0a35fe78-f5a9-4326-9ab6-37c9307b2da7)
![3](https://github.com/user-attachments/assets/ccaf303d-598a-452e-89ff-b928de107a70)
大佬再帮忙看下，文件写入之后，会自动退出断开，下周要交差

**Comment by zzxiaotian** [comment]
17:02:55 INFO WeChat SDK server is stopped
17:02:55 ERR PuppetBridge onError()
17:02:55 ERR [PadLocalDemo] on error: GError: Server selection timed out after 30000 ms
17:02:55 ERR WeChat SDK server stopped with error Server selection timed out after 30000 ms
17:02:55 VERB PuppetBridge onLogout()
17:02:55 VERB PuppetLoginMixin logout(logout) 这种问题有遇到过吗，我接收文本消息，保存之后，就会产生这个报错，然后退出程序

**Comment by zzxiaotian** [comment]
能加下我的tg：z xiaotian吗
